/** Generated by scripts/generate-favicon-assets.mjs — do not edit by hand. */

export const LL_MARK_VIEW_SIZE = 128;
export const LL_MARK_FONT_SIZE = 19.5;
export const LL_MARK_LEFT = { text: "Luque", x: 5.21, y: 81.42 } as const;
export const LL_MARK_RIGHT = { text: "Law", x: 83.51, y: 81.42 } as const;
export const LL_MARK_DOT = { cx: 72.78, cy: 71.86, r: 4.88 } as const;
