export const normReaderContent = {
  en: {
    modeLabel: "Reader",
    hint: "Full text on one page. Jump from the contents. Copy a link to share an article.",
    backArticles: "Article by article",
    openArticle: "Open this article",
    typeSize: "Text size",
    sizeS: "S",
    sizeM: "M",
    sizeL: "L",
    officialSource: "Official source",
    disclaimer:
      "For reference only. Colombian law changes; confirm the current official text before acting.",
    contents: "Contents",
    mobileContents: "Jump to section",
    mobileOpen: "Open",
    mobileClose: "Close",
    searchPlaceholder: "Filter titles, articles…",
    empty: "No matches in this norm.",
    expandAll: "Expand",
    collapseAll: "Collapse",
    sections: "sections",
    otherNorms: "Other norms",
  },
  es: {
    modeLabel: "Lectura continua",
    hint: "El texto completo en una sola página. Salta desde el índice. Copia el enlace para compartir un artículo.",
    backArticles: "Artículo por artículo",
    openArticle: "Abrir este artículo",
    typeSize: "Tamaño",
    sizeS: "S",
    sizeM: "M",
    sizeL: "L",
    officialSource: "Fuente oficial",
    disclaimer:
      "Solo referencia. La ley colombiana cambia; confirma el texto oficial vigente antes de actuar.",
    contents: "Contenido",
    mobileContents: "Ir a una sección",
    mobileOpen: "Abrir",
    mobileClose: "Cerrar",
    searchPlaceholder: "Filtrar títulos, artículos…",
    empty: "Sin coincidencias en esta norma.",
    expandAll: "Expandir",
    collapseAll: "Colapsar",
    sections: "secciones",
    otherNorms: "Otras normas",
  },
} as const;
